version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB:   ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    environment:
      # point at the postgres service on the Docker network
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
